### ISSUE TITLE
saving to private/ saves to public/

### ISSUE THREAD

**Issue by wrnice** [loureirorg/safe-vfs#1]
If I do the following : 

cd private/
nano testfile
type some stuff
ctrl O ctrl X

then testfile appears in the public/ folder

Same if I cp somefile from somewhere else to private/ folder. It goes to public/

**Comment by loureirorg** [comment]
Interesting. The code is using the "isPrivate" property to detect which folder each file belongs to (either /public or /private). But this property apparently doesn't exist anymore for files, only for folders (not 100% sure if in some point it existed). 

Anyway, to fix it, the code needs to read the isPrivate property of its container folder instead. 

Also, as this property is inherited from its container folder, and as the root folder ("/") is always private this means we cannot have files on the root of "/public", only folders.

**Comment by loureirorg** [comment]
Fixed in commit https://github.com/loureirorg/safe-vfs/commit/e372d7d825c6c3caff4bb22b68031bf01b43ccb5.

**Comment by wrnice** [comment]
I suppose having only folders on top of /public is coherent with the domain system, as each domain is a folder here. A file on top would be domain-orphan ? Ty for the fix !
